import './globals.css'
import { Exo_2 } from 'next/font/google'
import Navbar from '@/components/Navbar/Navbar';
import Footer from '@/components/Footer/Footer';
import AuthProvider from '@/components/AuthProvider/AuthProvider';
import { UserProvider } from '@/context/UserContext/UserContext';
import { JobProvider } from '@/context/JobContext/JobContext';
import { FilterProvider } from '@/context/FilterContext/FilterContext';

const exo = Exo_2({ subsets: ['latin'], weight: ['300', '400', '500', '600', '700', '800'], subsets: ['latin'], display: 'swap' });

export const metadata = {
  title: 'EZHire',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={exo.className}>
        <AuthProvider>
          <UserProvider>
            <JobProvider>
              <FilterProvider>
                <div className="container">
                  <Navbar />
                  {children}
                  <Footer />
                </div>
              </FilterProvider>
            </JobProvider>
          </UserProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
