import './globals.css';
import { Exo, Exo_2 } from 'next/font/google';
import 'react-toastify/dist/ReactToastify.css';
import Footer from '@/components/Footer/Footer';
import Navbar from '@/components/Navbar/Navbar';
import 'react-toastify/dist/ReactToastify.min.css';
import { ToastContainer } from '@/alerts/nextToast';
import { JobProvider } from '@/context/JobContext/JobContext';
import { UserProvider } from '@/context/UserContext/UserContext';
import AuthProvider from '@/components/AuthProvider/AuthProvider';
import { FilterProvider } from '@/context/FilterContext/FilterContext';

const exo2 = Exo_2({ subsets: ['latin'], weight: ['300', '400', '500', '600', '700', '800'], display: 'swap' });

export const metadata = {
  title: 'EZHire',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={exo2.className}>
        <AuthProvider>
          <UserProvider>
            <JobProvider>
              <FilterProvider>
                <div className="container">
                  <Navbar />
                  {children}
                  <Footer />
                </div>
                <ToastContainer position="top-center" autoClose={4000} limit={1} />
              </FilterProvider>
            </JobProvider>
          </UserProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
